// tests/cpom-showcase.spec.ts: a TOOL-OWNED (regenerated) worked example of the Component Page
// Object Model. It runs against self-contained markup via page.setContent — no app, no network,
// deterministically green — so it always reflects the current component library and reaches
// existing projects on re-run. It teaches: a Page Object composed of components, the terse child()
// helper for spec-ctor components, direct construction for role-union/portal widgets, table nesting
// (rows -> cells) with Collection cardinality, a portal Dialog resolved from the page root, and the
// universal actions + collection helpers every component inherits.
export function renderCpomShowcase(): string {
  return `import { test, expect } from '@playwright/test';
import { BasePage, Table, Dialog, Link, TextInput, NativeSelect } from '@components';

// Regenerated by framework — do not edit. Write your own tests in sibling files.
const HTML = \`
  <input aria-label="Search" />
  <select aria-label="Role filter">
    <option value="engineer">Engineer</option>
    <option value="admiral">Admiral</option>
  </select>
  <table>
    <thead>
      <tr><th>Name</th><th>Role</th></tr>
    </thead>
    <tbody>
      <tr><td>Ada</td><td>Engineer</td></tr>
      <tr><td>Grace</td><td>Admiral</td></tr>
    </tbody>
  </table>
  <a href="/next">Next</a>
  <div role="dialog" aria-label="Confirm">
    <h2>Delete?</h2>
    <button>Cancel</button>
  </div>
\`;

// A Page Object composed of components — the CPOM shape.
class ShowcaseScreen extends BasePage {
  readonly path = '/';

  // Spec-ctor components are declared with the terse child() helper.
  get search(): TextInput {
    return this.child(TextInput, { kind: 'role', role: 'textbox', name: 'Search' });
  }

  get role(): NativeSelect {
    return this.child(NativeSelect, { kind: 'role', role: 'combobox', name: 'Role filter' });
  }

  get next(): Link {
    return this.child(Link, { kind: 'role', role: 'link', name: 'Next' });
  }

  // Role-union / portal widgets carry their own resolution, so construct them directly.
  readonly people = new Table(this.page);
  readonly dialog = new Dialog(this.page);
}

test.describe('CPOM showcase (self-contained — no app needed)', () => {
  test('a page composes components; a table nests rows and cells', async ({ page }) => {
    await page.setContent(HTML);
    const screen = new ShowcaseScreen(page);

    // Collection cardinality via a web-first assertion (1 header row + 2 body rows = 3).
    await expect(screen.people.rows().locator).toHaveCount(3);

    // Nesting: locate a row by its text, then read a body cell inside it.
    await expect(screen.people.row('Ada').cell(1).locator).toHaveText('Engineer');
  });

  test('child() composes a primitive; a dialog resolves from the page root (portal)', async ({
    page,
  }) => {
    await page.setContent(HTML);
    const screen = new ShowcaseScreen(page);

    await expect(screen.next.locator).toHaveText('Next');
    await expect(screen.dialog.locator).toBeVisible();
    await expect(screen.dialog.button('Cancel').locator).toBeVisible();
  });

  test('universal actions and collection helpers', async ({ page }) => {
    await page.setContent(HTML);
    const screen = new ShowcaseScreen(page);

    // A universal action (fill) plus a web-first assertion on the exposed locator.
    await screen.search.fill('ada');
    await expect(screen.search.locator).toHaveValue('ada');

    // A native <select> handled by the NativeSelect primitive.
    await screen.role.selectOption({ label: 'Admiral' });
    await expect(screen.role.locator).toHaveValue('admiral');

    // Collection helpers: first()/last() alongside nth().
    await expect(screen.people.rows().first().locator).toContainText('Name');
    await expect(screen.people.rows().last().locator).toContainText('Grace');
  });
});
`;
}
