import type { StackProfile } from '../../types/stack-profile.js';

// eitr.config.ts: machine defaults OWNED and regenerated by the framework engine (testIdAttribute,
// trace, reporter, projects, testDir). baseURL is deliberately NOT here — it lives in the
// create-if-absent playwright.config.ts (which spreads these), so regenerating this file never
// clobbers the user's baseURL/config edits. `list` reporter gives console feedback; `html` is
// on-demand. testIgnore keeps any future `*.probe.*` file out of the run.
export function renderEitrConfig(profile: StackProfile, ciCd?: string): string {
  const framework = profile.framework.value;
  let serverCmd = 'npm run start';
  let serverPort = 3000;
  if (framework === 'react' || framework === 'vue' || framework === 'svelte') {
    serverCmd = 'npm run dev';
    serverPort = 5173;
  } else if (framework === 'angular') {
    serverCmd = 'npm run start';
    serverPort = 4200;
  }

  const reporters = ["['list']", "['html', { open: 'never' }]"];
  if (ciCd && ciCd !== 'none') {
    reporters.push("['junit', { outputFile: 'playwright-report/junit-results.xml' }]");
  }

  return `import { devices, type PlaywrightTestConfig } from '@playwright/test';

export const eitrConfig = {
  testDir: './tests',
  testIgnore: [/\\.probe\\./],
  fullyParallel: true,
  retries: process.env.CI ? 2 : 0,
  use: {
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: 10_000,
    navigationTimeout: 15_000,
    testIdAttribute: '${profile.testIdAttribute.value.replace(/'/g, "\\'")}',
  },
  reporter: [${reporters.join(', ')}],
  projects: [
    {
      name: 'chromium',
      testIgnore: [/.*\\.sanity\\.spec\\.(ts|js)/, /\\.probe\\./],
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'sanity',
      testDir: './tests/pom-sanity',
      testMatch: /.*\\.sanity\\.spec\\.(ts|js)/,
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  // webServer: {
  //   command: '${serverCmd}',
  //   url: 'http://localhost:${serverPort}',
  //   reuseExistingServer: !process.env.CI,
  // },
} satisfies Partial<PlaywrightTestConfig>;
`;
}
