// README.md for the generated project — the front door: what it is + how to run. create-if-absent.
export function renderProjectReadme(projectName: string, framework: string): string {
  let frameworkNote = '';
  if (framework === 'react') {
    frameworkNote =
      '\n> [!NOTE]\n> This E2E test suite targets a **React** application. If testing locally, make sure your React development server is running (usually `npm run dev` / Vite on port 5173, or `npm start` on port 3000).\n';
  } else if (framework === 'vue') {
    frameworkNote =
      '\n> [!NOTE]\n> This E2E test suite targets a **Vue** application. If testing locally, make sure your Vue development server is running (usually `npm run dev` on port 5173).\n';
  } else if (framework === 'angular') {
    frameworkNote =
      '\n> [!NOTE]\n> This E2E test suite targets an **Angular** application. If testing locally, make sure your Angular development server is running (usually `npm run start` / `ng serve` on port 4200).\n';
  } else if (framework === 'svelte') {
    frameworkNote =
      '\n> [!NOTE]\n> This E2E test suite targets a **Svelte** application. If testing locally, make sure your Svelte development server is running (usually `npm run dev` on port 5173).\n';
  }

  return `# ${projectName}

A Playwright + TypeScript UI-test framework core. It contains a typed component
library (\`components/\`) you build Page Objects on top of, a Playwright config, and one example test.

## Run

\`\`\`bash
npm install                      # install dependencies (Playwright, TypeScript)
npx playwright install chromium  # install the browser (one-time)
npm test                         # run the tests
\`\`\`
${frameworkNote}
The setup script runs these for you by default; if the browser step was blocked (e.g. antivirus), run the
two install commands above manually.

### Useful Commands

- **\`npm test\`** — runs all tests in headless mode.
- **\`npm run test:ui\`** — opens Playwright's interactive UI mode (highly recommended for debugging and writing tests visually!).
- **\`npm run report\`** — opens the HTML report of the last run.
- **\`npm run typecheck\`** — runs strict TypeScript compiler checks.
- **\`npm run format\`** — formats files using Prettier.

## Configure

- **\`playwright.config.ts\`** — your config; set \`baseURL\` to your app. Generated once, never overwritten.
- **\`components/\`** — the CPOM component library, generated once: \`base/\` (BasePage, Component,
  Container, Collection), \`primitives/\` (Button, TextInput, Checkbox, Select, NativeSelect, Radio, Link, FileInput,
  Heading, Element),
  \`widgets/\` (Dialog, Table). Build Page Objects on top; extend it from \`overrides/\`. Situational
  primitives your app may never need (a range slider, drag-and-drop, canvas drawing) aren't
  generated by default — ask your AI assistant to add one on demand; it knows the compliant pattern.
- **\`tests/\`** — your tests. \`smoke.spec.ts\` is your starting point.

## Working with AI Agents & SSO (Authentication)

If your application uses Single Sign-On (SSO) like Auth0, Okta, or Microsoft Entra, providing your base URL to the AI agent might redirect it to the login provider. This means the AI won't see your actual application to determine its tech stack and structure!

To fix this, you need to create an authenticated session state (\`storageState\`) that the AI can use to bypass login:

1. **Generate the State File:**
   Run Playwright's code generator, which opens a browser where you can manually log in:
   \`\`\`bash
   npx playwright codegen --save-storage=auth.json <YOUR_APP_URL>
   \`\`\`
2. **Log In:** Log into your application in the opened browser window. Once you see the main dashboard of your app, close the browser. A file named \`auth.json\` will be created.
3. **Instruct the AI:** Tell the AI agent to use this \`auth.json\` file for reconnaissance. It will inject your cookies and tokens into its browser, bypass the SSO redirect, and correctly analyze your real application.

> [!WARNING]
> \`auth.json\` contains sensitive session tokens. It is automatically ignored by Git (if you use standard Playwright ignores), but **never commit it or share it publicly**.

## Writing a Page Object

You don't need to know TypeScript generics to use this. Your own code has essentially no \`<...>\`:
extend \`BasePage\`, set a \`path\`, and declare components with \`child(...)\` (single) or \`list(...)\`
(a collection). Each \`child\` takes a component class and a locator spec:

\`\`\`ts
import { BasePage } from '@components/base/base-page';
import { Button, TextInput } from '@components/primitives';
import { Table } from '@components/widgets';

class DashboardPage extends BasePage {
  readonly path = '/dashboard';

  get search() { return this.child(TextInput, { kind: 'role', role: 'textbox', name: 'Search' }); }
  get submit() { return this.child(Button, { kind: 'role', role: 'button', name: 'Apply' }); }
  readonly people = new Table(this.page); // widgets with their own setup are constructed directly
}

// in a test:
const page = new DashboardPage(playwrightPage);
await page.goto();
await page.search.fill('ann');
await page.submit.click();
await expect(page.people.row('Ann').cell(1).locator).toHaveText('Admin');
\`\`\`

Where do the \`<...>\` come from? Only the \`components/\` library uses them (e.g. \`Collection<Row>\` =
"a collection of rows"). They're what makes autocomplete and type-checking work — \`people.rows().nth(0)\`
is known to be a \`Row\`, so \`.cell(...)\` is suggested and typos are caught. You read them, but you rarely
write them: your Page Objects and tests stay generics-free.

## Scripts

- \`npm test\` — run tests   ·   \`npm run test:ui\` — Playwright UI mode   ·   \`npm run report\` — open the HTML report
- \`npm run typecheck\` — \`tsc --noEmit\`
`;
}
